### ISSUE TITLE
Library not working even in example

### ISSUE THREAD

**Issue by Eliminateur** [Naguissa/uSevenSegmentLib#1]
Hello,
i'm running IDE 1.8.10 on a leonardo board, i'm using 3 displays without decimal dot connected, i've installed library usevensegment 1.0.0 and utimerlib 1.4.0 from the library manager.
Edited the sketch to not use the dot(i also changed it later to no avail) and it only shows broken characters and garbage on the displays.
Using your own 7 segment verification sketch modified to turn on all displays it shows all of the segments correctly.

i've even tried a most basic sketch to show "888" and it doesn't even work, it shows nothing, after some seconds an 8 appears on the last display, then it turns off. I've even included utimerlib by hand on the sketch to no avail.
Changing the sketch to "123" now displays all broken data

> 
> #include` "Arduino.h"
> #include "uSevenSegmentLib.h"
> #include "uTimerLib.h"
> 
> 	int pins[7] = {0, 1, 2, 3, 4, 5, 6};
> 	int muxes[3] = {7, 8, 9};
>  unsigned int freq=60;
> 
> 
> uSevenSegmentLib sevenSegments(3, pins, muxes);
> bool led_status = true;
> 
> 
> int i = 0;
> 
> void setup() {
> 	sevenSegments.set(0);
> 	sevenSegments.attachInterrupt();
> }
> 
> void loop() {
> 	sevenSegments.set(123);
> }
> 
> 
> 
>

**Comment by Naguissa** [comment]
I cannot test that micro now but I suspect from uTimerlib; could you check uTimerlib examples?

**Comment by Naguissa** [comment]
If timer doesn't work you can try adding this to loop():

uSevenSegmentLib::interrupt();

**Comment by Eliminateur** [comment]
i haven't been able to followup on the error as i've been using a different
liobrary for the 7-segments

**Comment by Naguissa** [comment]
OK, thanks. I'll close this issue and open a new one on uTimerLib, which is the one I think can have trouble with 32U4 boards. I'll check it when I find my board, or buy a new one (I have no idea where it can be).

Cheers!
