### ISSUE TITLE
ESP32 does not work

### ISSUE THREAD

**Issue by dbeavers** [Naguissa/uSevenSegmentLib#3]
This does not work with ESP-WROOM-32.  It interrupts before writing the segments.  I am using a 4 digit 7 segment display with 4 periods.

#include "Arduino.h"
#include "uSevenSegmentLib.h"

int pins[8]  = {32, 14, 12, 26, 25, 33, 13, 27};
int muxes[4] = {4, 0, 2, 15};

uSevenSegmentLib sevenSegments(4, pins, muxes);

int i = 0;

void setup() {
	sevenSegments.set(i);
	sevenSegments.attachInterrupt();
}

void loop() {
	delay(1000);
  i = (i + 1) % 10;
	sevenSegments.set(i);
}

**Comment by Naguissa** [comment]
I have to put it into documentation and create a new example, but this library can work in two modes:

1) With uTimerLib library using your example, attachInterrupt - https://github.com/Naguissa/uTimerLib

2) Without it, but using uSevenSegmentLib::interrupt


You can try this:

```
#include "Arduino.h"
#include "uSevenSegmentLib.h"

int pins[8] = {32, 14, 12, 26, 25, 33, 13, 27};
int muxes[4] = {4, 0, 2, 15};

uSevenSegmentLib sevenSegments(4, pins, muxes);

int i = 0;
unsigned long time_next = 0;


void setup() {
sevenSegments.set(i);
}

void loop() {
  uSevenSegmentLib::interrupt();
  if(millis() >= time_next){
    time_next = millis() + 1000;
    i = (i + 1) % 10;
    sevenSegments.set(i);
  }
}

```


(Edited to remove attachInterrupt in the code)

**Comment by dbeavers** [comment]
Sorry, same behavior.  It continually reboots:
14:25:43.258 -> ELF file SHA256: e7e9766582a281a6
14:25:43.258 -> 
14:25:43.258 -> E (149) esp_core_dump_flash: Core dump flash config is corrupted! CRC=0x7bd5c66f instead of 0x0
14:25:43.258 -> Rebooting...
14:25:43.258 -> ets Jul 29 2019 12:21:46
14:25:43.258 -> 
14:25:43.258 -> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
14:25:43.258 -> configsip: 0, SPIWP:0xee
14:25:43.258 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
14:25:43.290 -> mode:DIO, clock div:1
14:25:43.290 -> load:0x3fff0030,len:1344
14:25:43.290 -> load:0x40078000,len:13836
14:25:43.290 -> load:0x40080400,len:3608
14:25:43.290 -> entry 0x400805f0
14:25:43.387 -> 
14:25:43.387 -> assert failed: block_locate_free heap_tlsf.c:447 (block_size(block) >= size)
14:25:43.387 -> 
14:25:43.387 -> 
14:25:43.387 -> Backtrace: 0x40083351:0x3ffe38d0 0x400872a9:0x3ffe38f0 0x4008c0b1:0x3ffe3910 0x4008b24d:0x3ffe3a40 0x4008ba93:0x3ffe3a60 0x4008bd08:0x3ffe3a80 0x400835da:0x3ffe3aa0 0x400835ed:0x3ffe3ad0 0x400d870d:0x3ffe3af0 0x400d8a5b:0x3ffe3b50 0x400d8f04:0x3ffe3b80 0x400d8d97:0x3ffe3ba0 0x4008335f:0x3ffe3bd0 0x400d5dd9:0x3ffe3bf0 0x400d5ea9:0x3ffe3c10 0x40082a71:0x3ffe3c40 0x400792ca:0x3ffe3c90 |<-CORRUPTED

**Comment by Naguissa** [comment]
14:25:43.258 -> E (149) esp_core_dump_flash: Core dump flash config is corrupted! CRC=0x7bd5c66f instead of 0x0

Seens there's something wrong with your config flash, try flashing or cleaning that part.

**Comment by dbeavers** [comment]
That did not work.  I enabled "Erase all flash before upload" and still get the same results.  You should be able to reproduce this behavior with the same hardware that I am using.

**Comment by Naguissa** [comment]
I have not just that board, nor ESP32s. If you google just the error I pointed you can find this in 2nd place (GitHub result):

https://github.com/HomeSpan/HomeSpan/discussions/490

**Comment by dbeavers** [comment]
That link does not address the same problem.  He said that it works on the dual core ESP-WROOM-32 that I am using and does not work on the single core version that I am not using.

**Comment by Naguissa** [comment]
Updated library and checked on that micro.

**Comment by dbeavers** [comment]
I updated to 1.0.3 and it still is not working:

16:14:48.820 -> ELF file SHA256: 00e803c6cc909459
16:14:48.820 -> 
16:14:48.916 -> Rebooting...
16:14:48.916 -> ets Jul 29 2019 12:21:46
16:14:48.916 -> 
16:14:48.916 -> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
16:14:48.949 -> configsip: 0, SPIWP:0xee
16:14:48.949 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
16:14:48.949 -> mode:DIO, clock div:1
16:14:48.949 -> load:0x3fff0030,len:1344
16:14:48.949 -> load:0x40078000,len:13836
16:14:48.949 -> load:0x40080400,len:3608
16:14:48.949 -> entry 0x400805f0
16:14:49.076 -> Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
16:14:49.076 -> 
16:14:49.076 -> Core  1 register dump:
16:14:49.076 -> PC      : 0x400d1293  PS      : 0x00060030  A0      : 0x800d1343  A1      : 0x3ffb27c0  
16:14:49.076 -> A2      : 0x00000000  A3      : 0x3ffb08c0  A4      : 0x00000020  A5      : 0x80000000  
16:14:49.076 -> A6      : 0x3ffb7dbc  A7      : 0x80000001  A8      : 0x80000020  A9      : 0x00000007  
16:14:49.108 -> A10     : 0x00000005  A11     : 0x00000001  A12     : 0x00000000  A13     : 0x00000020  
16:14:49.108 -> A14     : 0x007bf2c8  A15     : 0x003fffff  SAR     : 0x00000000  EXCCAUSE: 0x0000001c  
16:14:49.108 -> EXCVADDR: 0x00000041  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  
16:14:49.108 -> 
16:14:49.108 -> 
16:14:49.108 -> Backtrace: 0x400d1290:0x3ffb27c0 0x400d1340:0x3ffb27e0 0x400d111f:0x3ffb2800 0x400d14b5:0x3ffb2820
16:14:49.140 -> 

Perhaps this will help: https://stackoverflow.com/questions/63399901/how-to-fix-guru-meditation-error-core-1-paniced-loadprohibited-error
This is probably more helpful: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/fatal-errors.html#loadprohibited-storeprohibited

**Comment by Naguissa** [comment]
May it have any problem with selected pins? Using main example with these ones it works:

```
	int pins[8] = {10, 11, 12, 13, 14, 15, 16, 17};
	int muxes[3] = {23, 24, 25};

```


EDIT: Also, check if you're using latest IDE version.

**Comment by dbeavers** [comment]
Neither suggestion work.  There are 12 ADC I/O pins total on this chip and the program uses only those.   I tried the online version (which should be the most up to date) and I still get the same results.
(LoadProhibited)  EXCVADDR: 0x00000041
